MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "HRNET"

  HRNET:
    AUTO_RESUME: true
    CUDNN:
      BENCHMARK: true
      DETERMINISTIC: false
      ENABLED: true
    DATA_DIR: ''
    GPUS: (0,1,2,3)
    OUTPUT_DIR: 'output'
    LOG_DIR: 'log'
    WORKERS: 24
    PRINT_FREQ: 100

    DATASET:
      COLOR_RGB: true
      DATASET: 'coco'
      DATA_FORMAT: jpg
      FLIP: true
      NUM_JOINTS_HALF_BODY: 8
      PROB_HALF_BODY: 0.3
      ROOT: 'data/coco/'
      ROT_FACTOR: 45
      SCALE_FACTOR: 0.35
      TEST_SET: 'val2017'
      TRAIN_SET: 'train2017'
    
    HRNET_DETAIL:
      INIT_WEIGHTS: true
      NAME: pose_hrnet
      NUM_JOINTS: 17
      PRETRAINED: 'models/pytorch/imagenet/hrnet_w32-36af842e.pth'
      TARGET_TYPE: gaussian
      IMAGE_SIZE:
      - 288
      - 384
      HEATMAP_SIZE:
      - 72
      - 96
      SIGMA: 3
      EXTRA:
        PRETRAINED_LAYERS:
        - 'conv1'
        - 'bn1'
        - 'conv2'
        - 'bn2'
        - 'layer1'
        - 'transition1'
        - 'stage2'
        - 'transition2'
        - 'stage3'
        - 'transition3'
        - 'stage4'
        FINAL_CONV_KERNEL: 1
        STAGE2:
          NUM_MODULES: 1
          NUM_BRANCHES: 2
          BLOCK: BASIC
          NUM_BLOCKS:
          - 4
          - 4
          NUM_CHANNELS:
          - 32
          - 64
          FUSE_METHOD: SUM
        STAGE3:
          NUM_MODULES: 4
          NUM_BRANCHES: 3
          BLOCK: BASIC
          NUM_BLOCKS:
          - 4
          - 4
          - 4
          NUM_CHANNELS:
          - 32
          - 64
          - 128
          FUSE_METHOD: SUM
        STAGE4:
          NUM_MODULES: 3
          NUM_BRANCHES: 4
          BLOCK: BASIC
          NUM_BLOCKS:
          - 4
          - 4
          - 4
          - 4
          NUM_CHANNELS:
          - 32
          - 64
          - 128
          - 256
          FUSE_METHOD: SUM
    LOSS:
      USE_TARGET_WEIGHT: true
    TRAIN:
      BATCH_SIZE_PER_GPU: 32
      SHUFFLE: true
      BEGIN_EPOCH: 0
      END_EPOCH: 210
      OPTIMIZER: adam
      LR: 0.001
      LR_FACTOR: 0.1
      LR_STEP:
      - 170
      - 200
      WD: 0.0001
      GAMMA1: 0.99
      GAMMA2: 0.0
      MOMENTUM: 0.9
      NESTEROV: false
  
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 256
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 2
  ROI_KEYPOINT_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "KeypointRCNNFeatureExtractor"
    PREDICTOR: "KeypointRCNNPredictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 56
    SHARE_BOX_FEATURE_EXTRACTOR: False
  KEYPOINT_ON: True
DATASETS:
  TRAIN: ("keypoints_coco_2017_train",)
  TEST: ("keypoints_coco_2017_val",)
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1000
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.0001
  STEPS: (1500,)
  MAX_ITER: 2000
  IMS_PER_BATCH: 4
TEST:
  IMS_PER_BATCH: 2
