MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    CONV_BODY: "HRNET"
  # WEIGHT: '../model_final.pth'

  HRNET:
    AUTO_RESUME: true
    CUDNN_BENCHMARK: true
    CUDNN_DETERMINISTIC: false
    CUDNN_ENABLED: true
    DATA_DIR: ''
    GPUS: (0,1,2,3)
    OUTPUT_DIR: 'output'
    LOG_DIR: 'log'
    WORKERS: 24
    PRINT_FREQ: 100


    DATASET_COLOR_RGB: true
    DATASET_DATASET: 'coco'
    DATASET_DATA_FORMAT: jpg
    DATASET_FLIP: true
    DATASET_NUM_JOINTS_HALF_BODY: 8
    DATASET_PROB_HALF_BODY: 0.3
    DATASET_ROOT: 'data/coco/'
    DATASET_ROT_FACTOR: 45
    DATASET_SCALE_FACTOR: 0.35
    DATASET_TEST_SET: 'val2017'
    DATASET_TRAIN_SET: 'train2017'
    
    DETAIL_INIT_WEIGHTS: true
    DETAIL_NAME: pose_hrnet
    DETAIL_NUM_JOINTS: 17
    DETAIL_PRETRAINED: 'models/pytorch/imagenet/hrnet_w32-36af842e.pth'
    DETAIL_TARGET_TYPE: gaussian
    DETAIL_IMAGE_SIZE:
    - 288
    - 384
    DETAIL_HEATMAP_SIZE:
    - 72
    - 96
    DETAIL_SIGMA: 3
    DETAIL_EXTRA:
      PRETRAINED_LAYERS:
      - 'conv1'
      - 'bn1'
      - 'conv2'
      - 'bn2'
      - 'layer1'
      - 'transition1'
      - 'stage2'
      - 'transition2'
      - 'stage3'
      - 'transition3'
      - 'stage4'
      FINAL_CONV_KERNEL: 1
      STAGE2:
        NUM_MODULES: 1
        NUM_BRANCHES: 2
        BLOCK: BASIC
        NUM_BLOCKS:
        - 4
        - 4
        NUM_CHANNELS:
        - 32
        - 64
        FUSE_METHOD: SUM
      STAGE3:
        NUM_MODULES: 4
        NUM_BRANCHES: 3
        BLOCK: BASIC
        NUM_BLOCKS:
        - 4
        - 4
        - 4
        NUM_CHANNELS:
        - 32
        - 64
        - 128
        FUSE_METHOD: SUM
      STAGE4:
        NUM_MODULES: 3
        NUM_BRANCHES: 4
        BLOCK: BASIC
        NUM_BLOCKS:
        - 4
        - 4
        - 4
        - 4
        NUM_CHANNELS:
        - 32
        - 64
        - 128
        - 256
        FUSE_METHOD: SUM
    LOSS_USE_TARGET_WEIGHT: false
      
    TRAIN_BATCH_SIZE_PER_GPU: 32
    TRAIN_SHUFFLE: true
    TRAIN_BEGIN_EPOCH: 0
    TRAIN_END_EPOCH: 210
    TRAIN_OPTIMIZER: adam
    TRAIN_LR: 0.001
    TRAIN_LR_FACTOR: 0.1
    TRAIN_LR_STEP:
    - 170
    - 200
    TRAIN_WD: 0.0001
    TRAIN_GAMMA1: 0.99
    TRAIN_GAMMA2: 0.0
    TRAIN_MOMENTUM: 0.9
    TRAIN_NESTEROV: false
  
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 2
  ROI_KEYPOINT_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "KeypointRCNNFeatureExtractor"
    PREDICTOR: "KeypointRCNNPredictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 56
    SHARE_BOX_FEATURE_EXTRACTOR: False
  KEYPOINT_ON: True

DATASETS:
  TRAIN: ("keypoints_coco_2017_train",)
  TEST: ("keypoints_coco_2017_val",)
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (480000, 640000)
  MAX_ITER: 720000
